const mongoose = require('mongoose');
Schema = mongoose.Schema;

// Define a new 'PromptSchema'
const PromptSchema = new Schema({
  chatId: { 
    type: String, 
    unique: true, 
    required: true 
  }, 
  prompt: String,
  response: String,
  createdAt: String,
  chatTitle: String,
  upVotes: { 
    type: Number, 
    min: 0, 
    max: 9999
  },
  downVotes: { 
    type: Number, 
    min: 0, 
    max: 9999
  },
})

// Create the 'Prompt' model out of the 'PromptSchema'
const Prompt = mongoose.model('Prompt', PromptSchema); 

// Export the 'Prompt' model
module.exports = Prompt;

/* •	chatId: String, unique identifier for each prompt/response pair.
•	prompt: String, the user's input text.
•	response: String, the response generated by the AI model.
•	createdAt: String, the date and time the prompt was created.
•	chatTitle: String, the title of the chat.
•	upVotes: Number, the number of upvotes the response has received.
•	downVotes: Number, the number of downvotes the response has received. */
